name = "remix-cloudflare-workers"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

kv_namespaces = [
    { binding = "AUTH_STORE", id = "83ebf7c034b84ac7bac80100acbe97e9" }
]